#!/bin/bash

Bookmarks=~/Documents/bookmarks

lines=$(cat $Bookmarks | tr "|" "\n")

readarray -t array <<<"$lines"


readarray -t urls < <(echo "$lines" | sed '1~2d')
readarray -t names < <(echo "$lines" | sed '0~2d')

var=$( IFS=$'\n'; echo "${names[*]}" )
output=$(echo "$var" | rofi -dmenu -p "Search")

for i in "${!names[@]}"; do
   if [[ "${names[$i]}" = "${output}" ]]; then
       firefox "${urls[$i]}"
       break
   fi
done


