#!/bin/bash

Bookmarks=~/Documents/bookmarks

readarray -t names <<<$(cut -d "|" -f 1 $Bookmarks)
readarray -t urls <<<$(cut -d "|" -f 2 $Bookmarks)

var=$( IFS=$'\n'; echo "${names[*]}" )
output=$(echo "$var" | rofi -dmenu -p "Firefox")

[[ -z "$output" ]] && exit 

for i in "${!names[@]}"; do
   if [[ "${names[$i]}" = "${output}" ]]; then
       firefox "${urls[$i]}"
       break
   fi
done
